group: motif
task: motif_point_test
test_split: test_au_tu
include: _default_template_motif_yaml
process_docs: !function utils_point.motif_preprocess_dataset
output_type: generate_until
doc_to_visual: !function utils_point.motif_doc_to_visual
doc_to_text: !function utils_point.motif_doc_to_text
doc_to_target: !function  utils_point.motif_doc_to_target
metadata:
  - version: 0.0
model_specific_prompt_kwargs:
  uipro_qwen2_vl:
    format: uipro_qwen2_vl
    post_prompt: |
      I want to {goal_info}. Please locate the target element I should interact with. (Output the center coordinates of the target)
  uipro_qwen2_vl_planning:
    format: uipro_qwen2_vl_planning
    post_prompt: |
      Given the UI screenshot and previous actions, please generate the next move necessary to advance towards task completion. The user's task is: I want to {goal_info}. Please locate the target element I should interact with. Touch the target element.
      Action history: Step 1. Travel to the user-specified page. Step 2. Swipe to the target element.
      
      Now, first describe the action intent and then directly plan the next action.
  uipro_florence2:
    format: uipro_florence2
    post_prompt: |
      I want to {goal_info}. Please locate the target element I should interact with. (Output the center coordinates of the target)
  uipro_llavaov:
    format: uipro_llavaov
    post_prompt: |
      I want to {goal_info}. Please locate the target element I should interact with. (Output the center coordinates of the target)
  uipro_internvl2:
    format: uipro_internvl2
    post_prompt: |
      I want to <ref>{goal_info}</ref>. Please locate the target element I should interact with. (Output the bounding box coordinates of the target)
  autogui_llava:
    format: autogui_llava
    post_prompt: |
      I want to {goal_info}. Please locate the target element I should interact with. (Output the center coordinates of the target)
  autogui:
    format: autogui
    ex_post_prompt: |
      Where is the "{goal_info}" element (with point)?
    post_prompt: |
      I will describe elements from a webpage screenshot; your role is to locate them (with point). {goal_info}
  autogui_qwen2_vl:
    format: autogui_qwen2_vl
    ex_post_prompt: |
      I want to {goal_info}. Please locate the target element I should interact with. (Output the center coordinates of the target)
    post_prompt: |
      Locate the element according to its detailed functionality description (Output the center coordinates of the target). The element is used to {goal_info}
  seeclick:
    format: seeclick
    post_prompt: |
      In the UI, where should I click if I want to complete instruction "{goal_info}" (with point)?
  tinyclick:
    format: tinyclick
    post_prompt: |
      What to do to execute the command? click on {goal_info}
  qwen_vl_chat:
    format: qwen_vl_chat
    post_prompt: |
      In the UI, where should I click if I want to complete instruction "{goal_info}" (with bounding box)?
  slime:
    format: qwen_vl_chat
    post_prompt: |
      What are the bounding box coordinates of the element corresponding to the command "{goal_info}" in this UI screenshot?
  cogagent_chat_hf:
    format: cogagent_chat_hf
    post_prompt: |
      Can you point out the element specified by the command "{goal_info}" in the UI screenshot and provide the bounding box of its location? (with grounding). 
  ferretui:
    format: ferretui
    post_prompt: |
      Where is the the element used to "{goal_info}"?
  uground:
    format: uground
    post_prompt: |
      Your task is to help the user identify the precise coordinates (x, y) of a specific area/element/object on the screen based on a description.

      - Your response should aim to point to the center or a representative point within the described area/element/object as accurately as possible.
      - If the description is unclear or ambiguous, infer the most relevant area or element based on its likely context or purpose.
      - Your answer should be a single string (x, y) corresponding to the point of the interest.

      Description: {goal_info}

      Answer:
  osatlas:
    format: osatlas
    post_prompt: |
      In this UI screenshot, what is the position of the element corresponding to the command "{goal_info}" (with bbox)?
  internvl2:
    format: internvl2
    post_prompt: |
      Please provide the bounding box coordinate of the UI element that fulfills this intent: <ref>{goal_info}</ref>'
  florence2:
    format: florence2
    post_prompt: |
      Locate the phrases in the caption: {goal_info}
  uground_llava:
    format: uground_llava
    post_prompt: |
      In the screenshot, where are the pixel coordinates (x, y) of the element corresponding to "{goal_info}"?
  osatlas4b:
    format: osatlas4b
    post_prompt: |
      In the screenshot of this web page, please give me the coordinates of the element I want to click on according to my instructions (with point).
      {goal_info}
process_results: !function utils_point.motif_point_process_results

model_specific_process_kwargs:
  uipro_qwen2_vl:
    scale: 1000
  uipro_qwen2_vl_planning:
    scale: 1000
  uipro_florence2:
    scale: 1000
  uipro_llavaov:
    scale: 1000
  uipro_internvl2:
    scale: 1000
  ferretui:
    scale: 1000
  autogui:
    scale: 100
  autogui_qwen2_vl:
    scale: 1000
  autogui_llava:
    scale: 1000
  uipro:
    scale: 100
  qwen_vl_chat:
    scale: 1000
  monkey:
    scale: 1000
  slime:
    scale: 100
  minicpm_v:
    scale: 1000
  tinyclick:
    scale: 1000
  qwen2_vl_cloud:
    scale: 1000
  qwen2_vl:
    scale: 1000
  llava_hf:
    scale: 100
  uground:
    scale: 1000
  osatlas:
    scale: 1000
  cogagent_chat_hf:
    scale: 1000
  internvl2:
    scale: 1000
  florence2:
    scale: 1000
  uground_llava:
    scale: 1000
  osatlas4b:
    scale: 1000
metric_list: # extract the value according to the metric: "key". Thus, the process_results should output the {key1: , key2: ...}
  - metric: motif_gnd_result
    aggregation: !function utils_point.motif_gnd_result
    higher_is_better: true
  # - metric: partial_action_bbox_acc # action_point
  #   aggregation: !function utils_point.motif_partial_aggregation_result
  #   higher_is_better: true
  # - metric: complete_action_bbox_acc
  #   aggregation: !function utils_point.motif_complete_aggregation_result
  #   higher_is_better: true
  # - metric: partial_action_acc
  #   aggregation: !function utils_point.motif_partial_aggregation_result
  #   higher_is_better: true
  # - metric: complete_action_acc
  #   aggregation: !function utils_point.motif_complete_aggregation_result
  #   higher_is_better: true
  # - metric: nogroup_action_bbox_acc
  #   aggregation: !function utils_point.motif_nogroup_aggregation_result
  #   higher_is_better: true


