group: motif
task: motif_point_test
test_split: test_au_tu
include: _default_template_motif_yaml
process_docs: !function utils_point.motif_preprocess_dataset
output_type: generate_until
doc_to_visual: !function utils_point.motif_doc_to_visual
doc_to_text: !function utils_point.motif_doc_to_text
doc_to_target: !function  utils_point.motif_doc_to_target
metadata:
  - version: 0.0
model_specific_prompt_kwargs:
  autogui:
    format: random
  seeclick:
    format: seeclick
    post_prompt: |
      In the UI, where should I click if I want to complete instruction "{goal_info}" (with point)?
  qwen_vl_chat:
    format: qwen_vl_chat
    post_prompt: |
      In the UI, where should I click if I want to complete instruction "{goal_info}" (with bounding box)?
  cogagent_chat_hf:
    format: cogagent_chat_hf
    pre_prompt: |
      Generate the target element according to the UI screenshot, instruction. Please provide the answer directly (with grounding). 
    post_prompt: |
      Instruction: {goal_info}.

process_results: !function utils_point.motif_point_process_results

model_specific_process_kwargs:
  autogui:
    scale: 100
  qwen_vl_chat:
    scale: 1000
  monkey:
    scale: 1000
  slime:
    scale: 100
metric_list: # extract the value according to the metric: "key". Thus, the process_results should output the {key1: , key2: ...}
  - metric: motif_gnd_result
    aggregation: !function utils_point.motif_gnd_result
    higher_is_better: true
  # - metric: partial_action_bbox_acc # action_point
  #   aggregation: !function utils_point.motif_partial_aggregation_result
  #   higher_is_better: true
  # - metric: complete_action_bbox_acc
  #   aggregation: !function utils_point.motif_complete_aggregation_result
  #   higher_is_better: true
  # - metric: partial_action_acc
  #   aggregation: !function utils_point.motif_partial_aggregation_result
  #   higher_is_better: true
  # - metric: complete_action_acc
  #   aggregation: !function utils_point.motif_complete_aggregation_result
  #   higher_is_better: true
  # - metric: nogroup_action_bbox_acc
  #   aggregation: !function utils_point.motif_nogroup_aggregation_result
  #   higher_is_better: true


