group: vwb_ag
dataset_path: HongxinLi/VWB-AG
task: vwb_ag_test
test_split: test
include: _default_template_vwb_yaml
output_type: generate_until
doc_to_visual: !function utils_point.vwb_doc_to_visual
doc_to_text: !function utils_point.vwb_doc_to_text
doc_to_target: !function  utils_point.vwb_doc_to_target
metadata:
  - version: 0.0
model_specific_prompt_kwargs:
  uipro_qwen2_vl:
    format: uipro_qwen2_vl
    post_prompt: |
      I want to {goal_info}. Please locate the target element I should interact with. (Output the center coordinates of the target)
  ferretui:
    format: ferretui
    post_prompt: |
      Provide the bounding boxes of the mentioned objects. {goal_info}
  autogui:
    format: autogui
    post_prompt: |
      Where is the "{goal_info}" element (with point)?
  tinyclick:
    format: tinyclick
    post_prompt: |
      What to do to execute the command? click on {goal_info}
  seeclick:
    format: seeclick
    post_prompt: |
      Given a screenshot, I will describe a specific element; your task is to predict their locations (with point). {goal_info}
  qwen_vl_chat:
    format: qwen_vl_chat
    pre_prompt: |
      Locate the element according to the UI screenshot and instruction, output the localized bounding box.
    post_prompt: |
      Instruction: {goal_info}.
  slime:
    format: qwen_vl_chat
    post_prompt: |
      What are the bounding box coordinates of the element corresponding to the command "{goal_info}" in this UI screenshot?
  cogagent_chat_hf:
    format: cogagent_chat_hf
    pre_prompt: |
      Generate the target element according to the UI screenshot, instruction. Please provide the answer directly (with grounding). 
    post_prompt: |
      Instruction: {goal_info}.
  deepseek_vl_chat:
    format: deepseek_vl_chat
    post_prompt: |
      In this UI screenshot, what is the position of the element corresponding to the command "{goal_info}"? Output the normalized X and Y coordinates, ranging from 0.0 to 1.0. Note that the X-axis runs horizontally from left (0.0) to right (1.0), and the Y-axis runs vertically from top (0.0) to bottom (1.0). Your should carefully view the image before finally predicting the required position in the format [X, Y].
  ferretui:
    format: ferretui
    post_prompt: |
      Where is the "{goal_info}"?
process_results: !function utils_point.vwb_point_process_results
model_specific_process_kwargs:
  uipro_qwen2_vl:
    scale: 1000
  ferretui:
    scale: 1000
  autogui:
    scale: 1000
  uipro:
    scale: 100
  qwen_vl_chat:
    scale: 1000
  monkey:
    scale: 1000
  slime:
    scale: 100
  minicpm_v:
    scale: 1000
  tinyclick:
    scale: 1000
  qwen2_vl_cloud:
    scale: 1000
  llava_hf:
    scale: 100
metric_list: # extract the value according to the metric: "key". Thus, the process_results should output the {key1: , key2: ...}
  - metric: vwb_action-gnd_result
    aggregation: !function utils_point.vwb_gnd_result
    higher_is_better: true
